name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        default: v1.0.7

jobs:
  build_and_release:
    name: Build for Multiple Platforms and Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      LATEST_TAG: ${{ inputs.tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Build for Linux and macOS using Makefile
        run: make all

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/gama-linux-amd64,release/gama-linux-arm64,release/gama-macos-amd64,release/gama-macos-arm64"
          draft: true

